#%RAML 1.0 DataType
type: object
properties: 
  description:
    type: string
    required: true
    description: Description message
    example: "HTTP POST on resource 'http://ptres-back-service.admision-ptres-p-ri:8080/ptres/api/v1/delivery' failed: internal server error (500)."
  link:
    type: string
    required: true
    description: Source link 
    example: "www.correos.es"