#%RAML 1.0 DataType
type: object
properties: 
  pdf:
    type: string
    required: false
    description: PDF document in base 64
    example: 'JVBERi0xLjQKJeLjz9MKMiAwIG9iago8PC9GaWx0ZXIvRmxhdGVEZWNvZGUvTGVuZ3RoIDY3MT4+c3RyZWFtCkiJdFPRatswFH039B/...'
  error:
    type: string
    required: false
    description: Error description
    example: 'Error'